import type React from "react";

const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: "fixed", top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)", zIndex: 1000,
    display: "flex", alignItems: "center", justifyContent: "center",
  },
  modal: {
    width: "90vw", maxWidth: 1100, height: "85vh",
    backgroundColor: "#1e293b", borderRadius: 12,
    display: "flex", flexDirection: "column", overflow: "hidden",
    boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
  },
  header: {
    display: "flex", justifyContent: "space-between", alignItems: "center",
    padding: "16px 24px", borderBottom: "1px solid #334155",
  },
  title: { color: "#f1f5f9", fontSize: 18, fontWeight: 700, margin: 0 },
  closeBtn: { background: "none", border: "none", color: "#94a3b8", fontSize: 20, cursor: "pointer" },
  tabBar: { display: "flex", borderBottom: "1px solid #334155", padding: "0 16px" },
  tab: {
    padding: "10px 16px", background: "none", border: "none",
    color: "#94a3b8", cursor: "pointer", fontSize: 13, fontWeight: 500,
    borderBottom: "2px solid transparent", transition: "all 0.2s ease",
  },
  tabActive: { color: "#60a5fa", borderBottom: "2px solid #60a5fa" },
  content: { flex: 1, overflow: "auto", padding: 20 },
  marketSearchWrap: {
    display: "flex", alignItems: "center", gap: 8,
    backgroundColor: "#0f172a", borderRadius: 10,
    border: "1px solid #334155", padding: "0 14px",
    marginBottom: 14, height: 44, transition: "border-color 0.2s ease",
  },
  marketSearchIcon: { fontSize: 16, flexShrink: 0, opacity: 0.6 },
  marketSearchInput: {
    flex: 1, border: "none", background: "none",
    color: "#f1f5f9", fontSize: 14, outline: "none", fontFamily: "inherit",
  },
  statsBar: { display: "flex", gap: 10, marginBottom: 16, flexWrap: "wrap" as const },
  statPill: {
    display: "flex", alignItems: "center", gap: 6,
    padding: "6px 14px", borderRadius: 20, border: "1px solid",
    backgroundColor: "#0f172a",
  },
  statPillValue: { fontSize: 18, fontWeight: 700, lineHeight: 1 },
  statPillLabel: { fontSize: 11, color: "#64748b", textTransform: "uppercase" as const, fontWeight: 500 },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 12 },
  mktCard: {
    backgroundColor: "#0f172a", borderRadius: 10,
    border: "1px solid #334155", padding: 14,
    display: "flex", flexDirection: "column", gap: 10,
    transition: "all 0.2s ease", cursor: "default",
  },
  mktCardTop: { display: "flex", flexDirection: "column", gap: 8 },
  mktAvatarRow: { display: "flex", alignItems: "center", gap: 8 },
  mktAvatar: {
    width: 32, height: 32, borderRadius: 8,
    backgroundColor: "#1e293b", border: "2px solid",
    display: "flex", alignItems: "center", justifyContent: "center",
    fontSize: 14, fontWeight: 700, color: "#f1f5f9", flexShrink: 0,
  },
  mktNameBlock: { display: "flex", alignItems: "center", gap: 8, flex: 1, minWidth: 0 },
  mktCardName: {
    color: "#f1f5f9", fontSize: 13, fontWeight: 600,
    overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" as const,
  },
  mktStateBadge: {
    fontSize: 10, padding: "2px 7px", borderRadius: 10,
    border: "1px solid", textTransform: "uppercase" as const, fontWeight: 500, flexShrink: 0,
  },
  mktStatsRow: { display: "flex", gap: 16 },
  mktStat: { display: "flex", alignItems: "baseline", gap: 3 },
  mktStatValue: { fontSize: 15, fontWeight: 700, color: "#e2e8f0", fontFamily: "monospace" },
  mktStatLabel: { fontSize: 10, color: "#64748b" },
  mktSubMetrics: { display: "flex", gap: 6, fontSize: 10, color: "#475569", flexWrap: "wrap" as const },
  mktActions: { display: "flex", gap: 6, flexWrap: "wrap" as const, borderTop: "1px solid #1e293b", paddingTop: 8 },
  mktActionBtn: {
    padding: "4px 10px", fontSize: 11, borderRadius: 5,
    backgroundColor: "#1e293b", color: "#94a3b8", border: "1px solid #334155",
    cursor: "pointer", transition: "all 0.15s ease", fontWeight: 500,
  },
  dot: { width: 8, height: 8, borderRadius: "50%", flexShrink: 0 },
  error: { color: "#ef4444", fontSize: 12 },
  ok: { color: "#4ade80", fontSize: 12 },
  hint: { color: "#64748b", fontSize: 12, margin: "4px 0" },
  code: { color: "#a5f3fc", fontSize: 11, fontFamily: "monospace", margin: "2px 0" },
  loading: { color: "#94a3b8", fontSize: 13 },
  form: { maxWidth: 600 },
  formGroup: { marginBottom: 12 },
  formRow: { display: "flex", gap: 12 },
  label: { color: "#94a3b8", fontSize: 12, display: "block", marginBottom: 4 },
  input: {
    width: "100%", padding: "8px 10px", borderRadius: 6,
    border: "1px solid #334155", backgroundColor: "#0f172a",
    color: "#e2e8f0", fontSize: 13, boxSizing: "border-box" as const,
  },
  select: {
    padding: "8px 10px", borderRadius: 6,
    border: "1px solid #334155", backgroundColor: "#0f172a",
    color: "#e2e8f0", fontSize: 13, minWidth: 160,
  },
  toolRow: { display: "flex", gap: 8, marginBottom: 6, alignItems: "center" },
  addBtn: {
    padding: "6px 12px", fontSize: 12, borderRadius: 6,
    backgroundColor: "transparent", color: "#60a5fa", border: "1px dashed #334155", cursor: "pointer",
  },
  formActions: { display: "flex", gap: 10, marginTop: 16 },
  cancelBtn: {
    padding: "8px 16px", borderRadius: 6, fontSize: 13,
    backgroundColor: "#334155", color: "#cbd5e1", border: "none", cursor: "pointer",
  },
  primaryBtn: {
    padding: "8px 20px", borderRadius: 6, fontSize: 13, fontWeight: 600,
    backgroundColor: "#3b82f6", color: "white", border: "none", cursor: "pointer",
  },
  resultPre: {
    marginTop: 12, padding: 12, borderRadius: 6,
    backgroundColor: "#0f172a", color: "#a5f3fc", fontSize: 11,
    maxHeight: 300, overflow: "auto", whiteSpace: "pre-wrap",
  },
  smallBtn: {
    padding: "3px 8px", fontSize: 11, borderRadius: 4,
    backgroundColor: "#334155", color: "#cbd5e1", border: "none", cursor: "pointer",
  },
  healthGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 12 },
  healthCard: { backgroundColor: "#0f172a", borderRadius: 8, padding: 14, border: "1px solid #334155" },
  healthCardHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 10 },
  stateTag: {
    marginLeft: "auto", fontSize: 10, padding: "2px 6px", borderRadius: 4,
    backgroundColor: "#1e293b", color: "#94a3b8", textTransform: "uppercase" as const,
  },
  healthStats: { marginBottom: 10 },
  healthRow: { display: "flex", justifyContent: "space-between", padding: "2px 0" },
  healthLabel: { color: "#64748b", fontSize: 11 },
  healthValue: { color: "#e2e8f0", fontSize: 12, fontWeight: 600, fontFamily: "monospace" },
  healthActions: { display: "flex", gap: 6 },
  searchBar: { display: "flex", gap: 10, marginBottom: 16 },
  searchList: { display: "flex", flexDirection: "column", gap: 8 },
  searchItem: { backgroundColor: "#0f172a", borderRadius: 8, padding: 12, border: "1px solid #334155" },
  searchItemHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 4 },
  serverTag: { fontSize: 10, padding: "1px 6px", borderRadius: 4, backgroundColor: "#1e3a5f", color: "#60a5fa" },
  scoreTag: {
    fontSize: 10, padding: "1px 6px", borderRadius: 4,
    backgroundColor: "#1e293b", color: "#fbbf24", marginLeft: "auto", fontFamily: "monospace",
  },
  searchDesc: { color: "#94a3b8", fontSize: 12, margin: 0 },
  graphCard: { backgroundColor: "#0f172a", borderRadius: 8, padding: 14, border: "1px solid #334155", marginBottom: 12 },
  mergeItem: { padding: "8px 0", borderBottom: "1px solid #1e293b" },
  depItem: { display: "flex", alignItems: "center", fontSize: 12, padding: "2px 0" },
  depType: {
    marginLeft: "auto", fontSize: 10, padding: "1px 5px",
    borderRadius: 3, backgroundColor: "#1e293b", color: "#64748b",
  },
  toolsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: 10 },
  toolCard: { backgroundColor: "#0f172a", borderRadius: 8, padding: 12, border: "1px solid #334155" },
  toolCardHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 6 },
  toolName: { color: "#e2e8f0", fontSize: 13, fontWeight: 600, fontFamily: "monospace" },
  toolServer: {
    fontSize: 10, padding: "1px 6px", borderRadius: 4,
    backgroundColor: "#1e3a5f", color: "#60a5fa", marginLeft: "auto",
  },
  toolDesc: { color: "#94a3b8", fontSize: 11, margin: 0, lineHeight: 1.4 },
  toolSchema: { marginTop: 8 },
  toolSchemaSummary: { fontSize: 10, color: "#64748b", cursor: "pointer" },
  toolSchemaPre: {
    marginTop: 4, padding: 8, borderRadius: 4,
    backgroundColor: "#0a0f1a", color: "#a5f3fc", fontSize: 10,
    maxHeight: 150, overflow: "auto", whiteSpace: "pre-wrap",
  },
  orphanSummaryBar: {
    backgroundColor: "#0f172a", borderRadius: 10,
    border: "1px solid #334155", padding: "14px 18px",
    marginBottom: 16, display: "flex", alignItems: "center",
    justifyContent: "space-between", flexWrap: "wrap" as const, gap: 8,
  },
  orphanSummaryText: { color: "#f1f5f9", fontSize: 14, fontWeight: 600 },
  orphanSummaryTags: { display: "flex", gap: 8, flexWrap: "wrap" as const },
  orphanTagDanger: {
    fontSize: 11, padding: "3px 10px", borderRadius: 12,
    backgroundColor: "rgba(239,68,68,0.15)", color: "#ef4444", fontWeight: 500,
  },
  orphanTagOk: {
    fontSize: 11, padding: "3px 10px", borderRadius: 12,
    backgroundColor: "rgba(74,222,128,0.15)", color: "#4ade80", fontWeight: 500,
  },
  orphanTagMuted: {
    fontSize: 11, padding: "3px 10px", borderRadius: 12,
    backgroundColor: "#1e293b", color: "#64748b",
  },
  orphanServerList: { display: "flex", flexDirection: "column", gap: 8 },
  orphanServerGroup: { backgroundColor: "#0f172a", borderRadius: 8, border: "1px solid #334155", overflow: "hidden" },
  orphanServerHeader: {
    width: "100%", display: "flex", alignItems: "center", gap: 8,
    padding: "10px 14px", background: "none", border: "none",
    color: "#e2e8f0", cursor: "pointer", fontSize: 13, fontWeight: 600,
    transition: "background 0.15s ease",
  },
  orphanChevron: { fontSize: 10, color: "#64748b", width: 12, textAlign: "center" as const },
  orphanServerName: { flex: 1, textAlign: "left" as const },
  orphanServerCount: { fontSize: 11, color: "#64748b", fontWeight: 400 },
  orphanToolList: { padding: "0 14px 10px", display: "flex", flexDirection: "column", gap: 6 },
  orphanToolCard: { backgroundColor: "#1e293b", borderRadius: 6, padding: 10, border: "1px solid #334155" },
  orphanToolHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 4 },
  orphanToolName: { color: "#e2e8f0", fontSize: 12, fontWeight: 600, fontFamily: "monospace" },
  orphanToolServer: {
    fontSize: 10, padding: "1px 6px", borderRadius: 4,
    backgroundColor: "#1e3a5f", color: "#60a5fa", marginLeft: "auto",
  },
  orphanToolDesc: { color: "#94a3b8", fontSize: 11, margin: "0 0 6px 0", lineHeight: 1.4 },
  orphanPaths: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" as const, marginBottom: 4 },
  orphanPathLabel: { fontSize: 10, color: "#64748b", fontWeight: 500 },
  orphanPathChip: { fontSize: 10, padding: "1px 6px", borderRadius: 4, backgroundColor: "#0f172a", color: "#94a3b8" },
  orphanWhy: {
    fontSize: 10, color: "#475569", fontStyle: "italic",
    backgroundColor: "rgba(251,191,36,0.08)", padding: "6px 10px",
    borderRadius: 4, margin: "4px 0", lineHeight: 1.5,
  },
  orphanSchemaToggle: {
    padding: "3px 10px", fontSize: 10, borderRadius: 4,
    backgroundColor: "#334155", color: "#94a3b8", border: "none", cursor: "pointer", marginTop: 2,
  },
  orphanSchemaPre: {
    marginTop: 6, padding: 8, borderRadius: 4,
    backgroundColor: "#0a0f1a", color: "#a5f3fc", fontSize: 10,
    maxHeight: 200, overflow: "auto", whiteSpace: "pre-wrap",
  },
};

export default styles;
